os: Windows Server 2012 R2
platform:
  - x64

clone_depth: 1

version: "{build}"

cache:
  - '%LOCALAPPDATA%\pip\Cache'

environment:
  global:
    CYGWIN_DIR: 'C:\cygwin64'
  matrix:
    - PYTHON_DIR: 'C:\Python34-x64'
      TOXENV: py34

    - PYTHON_DIR: 'C:\Python35-x64'
      TOXENV: py35


    - PYTHON_DIR: 'C:\Python35-x64'
      TOXENV: flake8

init:
  # Add Python to PATH
  - 'SET PATH=%PYTHON_DIR%;%PYTHON_DIR%\Scripts;%PATH%'

  # Add CYGWIN to PATH
  - 'SET PATH=%CYGWIN_DIR%\bin;%PATH%'
  - 'SET BORG_OPENSSL_PREFIX=%CYGWIN_DIR%\usr'
  - 'SET BORG_LZ4_PREFIX=%CYGWIN_DIR%\usr'

install:
  # Log info
  - 'python --version'
  - 'pip --version'
  - 'virtualenv --version'

  # Installing Dependencies using nuget
  - '%CYGWIN_DIR%\setup-x86_64.exe -q -P libopenssl -P openssl-devel -P liblz4_1 -P liblz4-devel -P fakeroot'

before_build:
  # Create build virtualenv
  - 'virtualenv --clear borg-env'
  - 'borg-env\Scripts\activate.bat'

  - 'pip install -r requirements.ddevelopment.txt'

build_script:
  - 'pip install -e .'

test_script:
  - 'tox -e %TOXENV% -r'