cache:
  - '%LOCALAPPDATA%\pip\Cache'

platform:
  - x64

environment:
  global:
    - CYGWIN_DIR: 'C:\\cygwin64'
  matrix:
    - PYTHON_DIR: "C:\\Python34-x64"
      TOXENV: py34

    - PYTHON_DIR: "C:\\Python35-x64"
      TOXENV: py35

install:
  # Add Python to PATH
  - "SET PATH=%PYTHON_DIR%;%PYTHON_DIR%\\Scripts;%PATH%"

  # Add CYGWIN to PATH
  - "SET PATH=%CYGWIN_DIR%\\bin;%PATH%"
  - "SET BORG_OPENSSL_PREFIX=%CYGWIN_DIR%\\usr"
  - "SET BORG_LZ4_PREFIX=%CYGWIN_DIR%\\usr"

  # Log info
  - "python --version"
  - "pip --version"
  - "virtualenv --version"

  # Installing Dependencies using nuget
  - "%CYGWIN_DIR%\\setup-x86_64.exe -q -P libopenssl -P openssl-devel -P liblz4_1 -P liblz4-devel"

  # Create build virtualenv
  - "virtualenv --clear .venv"
  - ".venv\\Scripts\\activate.bat"

  # Install the build dependencies of the project. If some dependencies contain
  # compiled extensions and are not provided as pre-built wheel packages,
  # pip will build them from source using the MSVC compiler matching the
  # target Python version and architecture
  - "pip install -r requirements.d/development.txt"

  # Updating Environment
  - pip install --upgrade setuptools
  - pip install --upgrade setuptools_scm
  - pip install --upgrade pip
  - pip install --upgrade wheel
  - pip install --upgrade tox

  # Install gg
  - "pip install -e ."

  # Print Python info
  - "pip freeze"

build: false

test_script:
  - "tox -r"