cache:
    - '%LOCALAPPDATA%\pip\Cache'

environment:
  matrix:
    - PYTHON_DIR: "C:\\Python34"
      TOXENV: py34

    - PYTHON_DIR: "C:\\Python35"
      TOXENV: py35

install:
  # Add Python to PATH
  - "SET PATH=%PYTHON_DIR%;%PYTHON_DIR%\\Scripts;%PATH%"

  - "python --version"
  - "nuget help"
  - "virtualenv --version"

  # Installing Dependencies using nuget
  - "nuget install lz4"
  - "nuget install openssl"

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - "pip install --disable-pip-version-check --user --upgrade pip"

  # Install the build dependencies of the project. If some dependencies contain
  # compiled extensions and are not provided as pre-built wheel packages,
  # pip will build them from source using the MSVC compiler matching the
  # target Python version and architecture
  - "pip install -r requirements.d/development.txt"
  - "pip install -e ."

  # Create build virtualenv
  - "virtualenv --clear %VENV_TEST_DIR%"
  - "%VENV_TEST_DIR%\\Scripts\\activate.bat"

  # Print Python info
  - "python ci\\info_platform.py"
  - "pip freeze"

test_script:
  - "tox -r"